# Generated by Django 5.0.2 on 2024-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='test1',
            field=models.CharField(default='', max_length=500),
        ),
    ]
