# Generated by Django 5.0.2 on 2024-03-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testa', '0002_notes_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
